[REQ-24] User/alanrazop/req 24 horas actualizadas
J-E-D-I-Software/CAEQ pull request #108
Opened 2023-11-10 22:27 UTC by alanrazop

**Análisis**

- https://www.notion.so/cvjj/Como-CAEQ-quiero-que-las-horas-de-capacitaci-n-de-un-colegiado-se-actualicen-autom-ticamente-cuando--f12bd7ba1cb64a6bafa3e82147e68ec6?pvs=4#aec97b755b2f40089dca1287a7c4aeb7

**Diseño**

- https://www.notion.so/cvjj/Como-CAEQ-quiero-que-las-horas-de-capacitaci-n-de-un-colegiado-se-actualicen-autom-ticamente-cuando--f12bd7ba1cb64a6bafa3e82147e68ec6?pvs=4#01b95c39189c48b18b89faba5bc4af76

**Pruebas**

- https://www.notion.so/cvjj/T-REQ24-Como-CAEQ-quiero-que-las-horas-de-capacitaci-n-de-un-colegiado-se-actualicen-autom-ticamen-f2118270404b4722bc3ed6b823cb590e

**Acciones necesarias para probar la implementación**

Es necesario hacer cambios en las variables de entorno (el archivo .env)? No
Es necesario generar directorios o archivos ignorados por git? No
Es necesario instalar/actualizar librerías de npm? No
Comando para correr la implementación npm run start:dev

2023-11-13 22:21 UTC, CesarJimenezVilleda02 requested changes
Atender los comentarios.

2023-11-13 22:21 UTC, CesarJimenezVilleda02 commented on caeq-backend/controllers/course.controller.js
> +exports.calculateAccreditedInscription = catchAsync(async (req, res, next) => {
Aplica el estándar a tu función

2023-11-13 22:21 UTC, CesarJimenezVilleda02 commented on caeq-backend/controllers/inscription.controller.js
> +        .sort({ updatedAt: -1 });
Este sort no es necesario

2023-11-13 22:21 UTC, CesarJimenezVilleda02 commented on caeq-web-portal/src/client/Inscription/Inscription.GET.js
> +export async function getCourseHours(id) {
Agregar documentación

2023-11-14 22:28 UTC, CesarJimenezVilleda02 approved these changes
Se ve bien y sigue el estándar. Gracias por atender mis comentarios.

2023-11-15 03:08 UTC, Lalo2077 commented on caeq-backend/controllers/inscription.controller.js
¿Es necesario este comentario?

2023-11-15 03:11 UTC, Lalo2077 commented on caeq-backend/tests/caeqUsers/caeq.users.accept.test.js
¿es necesario este console log agregado?

2023-11-15 03:34 UTC, Lalo2077 approved these changes

2023-11-15 03:35 UTC, merged