User/alanrazop/req 37 datos publicos
J-E-D-I-Software/CAEQ pull request #42
Opened 2023-10-17 14:33 UTC by alanrazop

- **Análisis**
Se enlistan los productos de trabajo generados en la etapa de análisis.
https://www.notion.so/cvjj/Como-arquitecto-quiero-que-mis-datos-de-contacto-curr-culum-y-especialidad-sean-p-blicos-para-ser-c-54a99bea192346d7b97fea9e82305fd7?pvs=4#ee69bae20d6846acba13b8a9edec27b2

- **Diseño**
Se enlistan los productos de trabajo generados en la etapa de diseño.
https://www.notion.so/cvjj/Como-arquitecto-quiero-que-mis-datos-de-contacto-curr-culum-y-especialidad-sean-p-blicos-para-ser-c-54a99bea192346d7b97fea9e82305fd7?pvs=4#ff9832a367a24907a6d1bdfcb4a7f115

- **Pruebas**
Se vincula el documento de detalles de prueba para este requisito.
https://www.notion.so/cvjj/T-REQ37-Como-arquitecto-quiero-que-mis-datos-de-contacto-curr-culum-y-especialidad-sean-p-blicos--9b7fcbeea47f43509284f4dea4f4d199

- **Acciones necesarias para probar la implementación:**
Es necesario hacer cambios en las variables de entorno (el archivo .env) NO
Es necesario generar directorios o archivos ignorados por git? NO
Es necesario instalar/actualizar librerías de npm? NO
Comando para correr la implementación npm run start:dev

2023-10-17 22:01 UTC, CesarJimenezVilleda02 commented on caeq-backend/controllers/architect.user.controller.js
> +        data: {
Agregar propiedad results

`results: documents.length`

2023-10-17 22:43 UTC, CesarJimenezVilleda02 requested changes
Por favor atiende los cambios.

2023-10-17 22:43 UTC, CesarJimenezVilleda02 commented on caeq-backend/controllers/architect.user.controller.js
> +    if (!documents || documents.length === 0) {
Eliminar este error. Se debe contemplar que puede no haber datos y esto no seria un error. La tabla se encarga del manejo de respuestas sin datos.

Probar eliminando los daatos de prueba de arquitectos temporalmente.

2023-10-17 22:43 UTC, CesarJimenezVilleda02 commented on caeq-backend/tests/directoryArchitectDetails/directoryArchitectPublic.get.test.js
> +    expect(res.statusCode).toEqual(200); //
Prueba que un documento no tenga propiedades que no son publicas.

2023-10-17 22:43 UTC, CesarJimenezVilleda02 commented on caeq-web-portal/src/client/ArchitectUser/ArchitectUser.GET.js
>  const paginationPageLimit = process.env.PAGINATION_PAGE_LIMIT || 5;
Aumenta este limite a 100

2023-10-17 22:43 UTC, CesarJimenezVilleda02 commented on caeq-web-portal/src/components/table/PublicTable.jsx
> +//
Los comentarios deben ser en español

2023-10-17 22:43 UTC, CesarJimenezVilleda02 commented on caeq-web-portal/src/screens/Landing/landingCAEQ.scss
> +    // background-color: rgba(
Eliminar comentarios no usados

2023-10-17 22:43 UTC, CesarJimenezVilleda02 commented on caeq-web-portal/src/screens/Landing/landingCAEQ.scss
> +/* Estilos para el contenedor principal */
Eliminar

2023-10-17 22:43 UTC, CesarJimenezVilleda02 commented on caeq-web-portal/src/screens/Landing/LandingCAEQ.js
> +                        <Link to='/SignupAdmin'>
Deberías agregar una forma para que los administradores vuelvan a la página.

2023-10-17 22:43 UTC, CesarJimenezVilleda02 commented on caeq-web-portal/src/screens/Landing/LandingCAEQ.js
> +    //const navigate = useNavigate();
Eliminar código comentado.

2023-10-20 17:52 UTC, MonseMoreno commented on caeq-web-portal/src/components/images/backgroundAdmin.png
Hay que buscar una imágen mas HD, esa se ve un poco pixeleada

2023-10-20 18:11 UTC, MonseMoreno commented on caeq-web-portal/src/screens/Landing/LandingArchitect.js
> +                    <InputText
te recomendaría quitar la barra de búsqueda o ajustarla para búscar algún parámetro en específico ya que la búsqueda general no funciona muy bien

2023-10-24 14:41 UTC, CesarJimenezVilleda02 approved these changes

2023-10-24 15:46 UTC, merged