Develop to master
J-E-D-I-Software/CAEQ pull request #83
Opened 2023-11-01 18:27 UTC by jorgeCastro-CVJJ

# Versión 1.0.1

- Ahora la fecha de nacimiento aparece correctamente en Perfil y Editar Perfil.
- La Edad es calculada y no se puede editar de manera aislada.
- El Directorio muestra un botón 'No hay CV registrado' cuando no hay CV.
- Los enlaces de descarga de CV ya te descargan el archivo.
- UnitTesting automática.

2023-11-02 23:45 UTC, black4ninja reviewed
Se requieren revisar todos los archivos y líneas del PR?

2023-11-02 23:51 UTC, jorgeCastro-CVJJ commented
> Se requieren revisar todos los archivos y líneas del PR?

No se requieren revisar todos lo archivos ni líneas del PR.
Más que nada es pasar lo que tenemos de Develop a Master para hacer el Release de la versión 1.0.1.

Acabo de modificar la descripción indicando que la revisión se en cerciorarse que los errores han sido resueltos.

2023-11-02 23:52 UTC, Leonardo812 approved these changes

2023-11-03 01:41 UTC, Luis-ERP requested changes

2023-11-03 01:41 UTC, Luis-ERP commented on caeq-backend/utils/email.js
> +const pug = require("pug");
El estandar son single quotes

2023-11-03 01:41 UTC, Luis-ERP commented on caeq-web-portal/src/client/stats.js
> +export async function getSpecialties(collegiateNumber) {
Falta agregar la descripción, parámetros y return en un bloque de comentarios

2023-11-03 01:41 UTC, Luis-ERP commented on caeq-web-portal/src/screens/AcceptAdmin/AcceptAdmin.js
> +                'Hemos tenido problemas enviando un correo de verificacion. El usuario ha sido verificado.'
Error de ortografía "Hemos tenido problemas enviando un correo de verificacion" cambiar a "Hemos tenido problemas enviando un correo de verificación"

2023-11-03 01:41 UTC, Luis-ERP commented on caeq-web-portal/src/screens/AcceptAdmin/AcceptAdmin.js
> +                'Hemos tenido problemas enviando un correo de verificacion. El usuario ha sido eliminado.'
Error de ortografía "Hemos tenido problemas enviando un correo de verificacion" cambiar a "Hemos tenido problemas enviando un correo de verificación"

2023-11-03 01:41 UTC, Luis-ERP commented on caeq-web-portal/src/screens/Directory/Directory.js
> +                'No puedes ingresar un rango de fecha de admisión con la fecha limite menor a la de inicio.'
Cambiar a lenguaje formal

2023-11-03 01:41 UTC, Luis-ERP commented on caeq-web-portal/src/screens/Directory/Directory.js
> +                'No puedes ingresar un rango de fecha de nacimiento con la fecha limite menor a la de inicio.'
Cambiar a lenguaje formal

2023-11-03 01:41 UTC, Luis-ERP commented on caeq-web-portal/src/screens/DirectoryArchitectDetail/DirectoryArchitectDetails.js
> +                    (i) Modifica la información que sea necesaria. Al terminar, haz clic
Cambiar a lenguaje formal

2023-11-03 01:41 UTC, Luis-ERP commented on caeq-web-portal/src/screens/DirectoryArchitectDetail/DirectoryArchitectDetails.js
> +                        label='Poliza de Seguro'
Error de ortografía: "Poliza de Seguro" a "Póliza de Seguro"

2023-11-03 01:41 UTC, Luis-ERP commented on caeq-web-portal/src/screens/Principal/Principal.js
> +          <p>En esta sección podras visualizar los proximos cursos impartidos por el Colegio. Además, tendrás la oportunidad de acceder a los detalles de cada curso, incluyendo información sobre la f
Error de ortografía "proximos" a "próximos"

2023-11-03 01:41 UTC, Luis-ERP commented on caeq-web-portal/src/screens/Principal/Principal.js
> +          <p>En esta sección podras visualizar tus datos personales, tu información del CAEQ y tu información profesional. Además, tendrás la oportunidad de editar tu información personal.</p>
Error de ortografía: "podras" a "pódras"

2023-11-03 01:41 UTC, Luis-ERP commented on caeq-web-portal/src/screens/Profile/EditProfile.js
> +            FireSucess('Los Cambios se han guardado correctamente');
Error de ortografía, "Cambios" a "cambios"

2023-11-03 01:41 UTC, Luis-ERP commented on caeq-web-portal/src/screens/SignupAdmin.js
> +                <h3>Confirmar Contraseñaaa</h3>
Error de ortografía "Contraseñaaa" a "Contraseña"

2023-11-03 22:47 UTC, Leonardo812 approved these changes

2023-11-03 23:47 UTC, CesarJimenezVilleda02 approved these changes
Buen trabajo compañero

2023-11-04 00:01 UTC, merged