User/leonardo812/req16 inscripcion
J-E-D-I-Software/CAEQ pull request #86
Opened 2023-11-02 00:37 UTC by Leonardo812

Análisis:
https://www.notion.so/cvjj/Como-arquitecto-quiero-inscribirme-y-pagar-mis-cursos-usando-el-nuevo-sistema-para-no-tener-que-ir-a-1d918ef7277f4e5983eaf156c806adf8?pvs=4

Diseño:
https://www.notion.so/cvjj/Como-arquitecto-quiero-inscribirme-y-pagar-mis-cursos-usando-el-nuevo-sistema-para-no-tener-que-ir-a-1d918ef7277f4e5983eaf156c806adf8?pvs=4

Pruebas:
https://www.notion.so/cvjj/T-REQ16-Como-arquitecto-quiero-inscribirme-y-pagar-mis-cursos-usando-el-nuevo-sistema-para-no-tene-c1308d5c5228455791fecf2a5605ba8a?pvs=4

Acciones necesarias para probar la implementación:

Es necesario hacer cambios en las variables de entorno (el archivo .env)? No
Es necesario generar directorios o archivos ignorados por git? No
Es necesario instalar/actualizar librerías de npm? No

2023-11-02 01:54 UTC, Luis-ERP requested changes

2023-11-02 01:54 UTC, Luis-ERP commented on caeq-backend/controllers/password.controller.js
> +    if (frontDomain === 'localhost:3000') {
Mejor usar la variable de entorno NODE_ENV == 'dev' porque puedes correr el front en otro puerto o en 127.0.0.1

2023-11-02 01:54 UTC, Luis-ERP commented on caeq-backend/controllers/password.controller.js
> +    if (frontDomain === 'localhost:3000') {
Lo mismo aquí que en comentario arriba

2023-11-02 01:54 UTC, Luis-ERP commented on caeq-backend/controllers/payment.controller.js
> +    if (course.cost == 0) {
Usa ===

2023-11-02 01:54 UTC, Luis-ERP commented on caeq-backend/controllers/payment.controller.js
> +    if (course.capacity == 0) {
Usar ===

2023-11-02 01:54 UTC, Luis-ERP commented on caeq-backend/controllers/payment.controller.js
> +    if (payment.status != 'Pendiente') {
Usar !==

2023-11-02 01:54 UTC, Luis-ERP commented on caeq-backend/controllers/payment.controller.js
> +    if (payment.status != 'Pendiente') {
Usar !==

2023-11-02 01:54 UTC, Luis-ERP commented on caeq-backend/utils/email.js
> +            "Gracias por inscribirte",
Mensaje formal

2023-11-02 01:54 UTC, Luis-ERP commented on caeq-backend/views/emails/inscriptionAlert.pug
> +  p #{course.description}
Usar lenguaje formal

2023-11-02 01:54 UTC, Luis-ERP commented on caeq-web-portal/src/screens/Courses/Course.js
> +            const swal = FireLoading('Inscribiéndote al curso...');
Usar lenguaje formal

2023-11-02 01:54 UTC, Luis-ERP commented on caeq-web-portal/src/screens/Courses/Course.js
> +            FireError('Por favor, selecciona un archivo de comprobante de pago.');
Usar lenguaje formal

2023-11-02 02:57 UTC, Leonardo812 commented on caeq-backend/views/emails/inscriptionAlert.pug
> +  p #{course.description}
Actualmente los correos estan comentandos dentro del payment.controller. Los templates seran creados en la pr de @jorgeCastro-CVJJ

2023-11-02 15:37 UTC, black4ninja reviewed
Revisar los comentarios, nada crítico solo legibilidad de código

2023-11-02 15:37 UTC, black4ninja commented on caeq-backend/app.js
> +app.use(function (req, res, next) {
Agreguen un comentario para identificar que estos header se ejecutan en cada llamada al backend, se entiende pero alguien nuevo en el desarrollo puede no entender que está pasando.

2023-11-02 15:37 UTC, black4ninja commented on caeq-backend/app.js
> +    //res.setHeader("Content-Security-Policy", "script-src 'self' 'unsafe-inline' *");
Si no se ocupan mejor eliminenlos

2023-11-02 15:37 UTC, black4ninja commented on caeq-backend/app.js
> +    helmet.contentSecurityPolicy({
No podrían combinar esta parte con el método de arriba? Este comportamiento puede llevar a que se ejecute solo 1 parte

2023-11-02 15:37 UTC, black4ninja commented on caeq-backend/controllers/inscription.controller.js
> +    if (course.startDate < new Date()) {
No tienen problemas con el timezone del servidor?

2023-11-02 15:37 UTC, black4ninja commented on caeq-backend/controllers/inscription.controller.js
> +   /* try {
Código sin usar mejor eliminenlo

2023-11-02 15:37 UTC, black4ninja commented on caeq-backend/controllers/password.controller.js
> +            'Hubo un error enviando el correo de reset password. Intenta de nuevo',
Ya se lo había mencionado a alguien en un review, pero consideren como buena práctica almacenar los strings del sistema en un archivo de constantes esto para tener un control centralizado de los errores y evitar typos o duplicar cuando son mensajes del sistema, lo ideal es separar los mensajes de UI ya que estos pueden llegar a ser traducidos por internacionalización, y string que solo se utilizan el código.

2023-11-02 15:37 UTC, black4ninja commented on caeq-backend/controllers/password.controller.js
> +    user.changedPasswordToken = undefined;
Es necesario asignar el undefined?

2023-11-02 15:37 UTC, black4ninja commented on caeq-backend/controllers/password.controller.js
> +        message: 'Contraseña cambiada con exito. Quiza debas iniciar sesion de nuevo',
Acentos

2023-11-02 15:37 UTC, black4ninja commented on caeq-backend/controllers/password.controller.js
> +        res.status(200).json({
Indentación de la última parte

2023-11-02 15:37 UTC, black4ninja commented on caeq-backend/controllers/payment.controller.js
> +    {
Estandarización de los json, cual es el formato correcto el de arriba de una línea o el de abajo separado.

2023-11-02 15:37 UTC, black4ninja commented on caeq-backend/controllers/payment.controller.js
> +            new AppError('Ya has empezado tu proceso de pago para este curso.', 400)
A esto me refiero con estandarizar los strings en un archivo de constantes para evitar reescribir cada mensaje, lo mismo para los códigos de error por ejemplo

2023-11-02 15:37 UTC, black4ninja commented on caeq-backend/controllers/payment.controller.js
> +    try {
Si no se utiliza eliminenlo.

2023-11-02 15:37 UTC, black4ninja commented on caeq-backend/controllers/payment.controller.js
> +    try {
Si no se utiliza eliminenlo

2023-11-02 15:37 UTC, black4ninja commented on caeq-backend/models/payment.model.js
> +        // TODO: que este campo sea read_only desde el front ybi que lo rellene el controlador dependiendo de lo que diga Stripe
Son necesarios los TODO?

2023-11-02 15:37 UTC, black4ninja commented on caeq-backend/models/payment.model.js
> +module.exports = Payment;
Agrega un newline al final de los archivos por facilidad para el linter como buena práctica.

2023-11-02 15:37 UTC, black4ninja commented on caeq-backend/routes/payment.route.js
> +router
Por legibilidad separar las rutas GET y POST, si funciona bien no pasa nada pero si alguien no está acostumbrado no va a entender que se está ejecutando.

2023-11-02 15:40 UTC, black4ninja commented
Chequen como están haciendo sus integraciones muchos archivos que revise están con cambios en otro PR

2023-11-06 22:19 UTC, Luis-ERP approved these changes

2023-11-06 22:23 UTC, CesarJimenezVilleda02 commented on caeq-backend/controllers/password.controller.js
> +    user.changedPasswordToken = undefined;
Si, de esta manera no se almacena la propiedad en Mongo y se elimina este campo del documento.

2023-11-06 22:23 UTC, CesarJimenezVilleda02 commented on caeq-backend/controllers/password.controller.js
> +            'Hubo un error enviando el correo de reset password. Intenta de nuevo',
Gracias lo tendremos en cuenta cuando hagamos refactorización.

2023-11-06 22:24 UTC, merged